[project]
name = "neetcode-algorithms-and-data-structures-for-beginners"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "notebook>=7.4.5",
    "polars>=1.32.3",
]
